idb_path: "Dropbox/aims_db/general_motion_mixed_depth.idb"
odb_path: "Dropbox/aims_db/general_motion_mixed_depth.odb"

gravity: [0, 0, -9.79343]

time_calibrate: 5
time_start: 6
time_end: 80.
dt: 0.005

# camera parameters
camera:
  fx: 432.84104727625214 # pixels
  fy: 432.925327181836 # pixels
  cx: 317.6920634353158 # pixels
  cy: 251.17163256628555 # pixels
  pixel_noise: 0.3
  distortion: [-0.29932978711199204, 0.09469642895565503, 8.98894755601866e-05, 0.000298086422736973, 0.0]

# imu parameters
imu:
  gyro_noise: 0.001
  gyro_walk: 0.00004
  accel_noise: 0.015
  accel_walk: 0.0002

rangefinder:
  range_noise: 0.002

# intersensor parameters
intersensor:
  p_c_i: [-0.05, 0., 0.]
  p_r_i: [0.1842, 0 ,0.06846]
  q_ic: [0.5, 0.5,  0.5,  0.5]
  q_ir: [0, 0, 0, 1.]

# initial conditions
x0:
  p_i_w: [-3.27632 ,  3.679856,  0.788 ] # m
  v_i_w: [0., 0., 0.] # m/s
  q_wi: [ 0.016676,  0.999844,  0.005813,  0.000199]


  gyro_bias: [-0.012205, -0.000213, -0.006672] # rad/s
  accel_bias: [0.026356, -0.014315, -0.057953] # m/s^2


# initial 3 sigma bounds
x0_3_sigma:
  p_i_w: 0.001 # m
  v_i_w: 0.001 # m/s
  theta_ic: 1 # degrees
  gyro_bias: 0.01 # rad/s
  accel_bias: 0.01 # m/s^2
